# Generated by Django 2.1.9 on 2019-06-27 23:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('phrf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cert',
            name='expiration_date',
            field=models.DateField(db_index=True),
        ),
    ]
