# Generated by Django 6.1 on 2026-09-01 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrf', '0004_alter_boat_id_alter_boat_year_alter_cert_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
