# Generated by Django 2.0.4 on 2018-04-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='zip',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
