# Generated by Django 2.0.4 on 2018-04-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180430_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='zip',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
