# Generated by Django 2.0.4 on 2018-04-30 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20180430_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='address1',
            new_name='address_1',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='address2',
            new_name='address_2',
        ),
    ]
